[package]
name = "rtensor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_approx_eq = "1.1.0"
nalgebra = "0.32.5"
rand = "0.8.5"

[profile.release]
opt-level = 3
panic = "abort"